const pool = require('../database/sqlConfig');


const countryMap = {
  "AF": "./public/maps/af.svg",
  "AL": "./public/maps/al.svg",
  "DZ": "./public/maps/dz.svg",
  "AS": "./public/maps/as.svg",
  "AD": "./public/maps/ad.svg",
  "AO": "./public/maps/ao.svg",
  "AI": "./public/maps/ai.svg",
  "AQ": "./public/maps/aq.svg",
  "AG": "./public/maps/ag.svg",
  "AR": "./public/maps/ar.svg",
  "AM": "./public/maps/am.svg",
  "AW": "./public/maps/aw.svg",
  "AU": "./public/maps/au.svg",
  "AT": "./public/maps/at.svg",
  "AZ": "./public/maps/az.svg",
  "BS": "./public/maps/bs.svg",
  "BH": "./public/maps/bh.svg",
  "BD": "./public/maps/bd.svg",
  "BB": "./public/maps/bb.svg",
  "BY": "./public/maps/by.svg",
  "BE": "./public/maps/be.svg",
  "BZ": "./public/maps/bz.svg",
  "BJ": "./public/maps/bj.svg",
  "BM": "./public/maps/bm.svg",
  "BT": "./public/maps/bt.svg",
  "BO": "./public/maps/bo.svg",
  "BA": "./public/maps/ba.svg",
  "BW": "./public/maps/bw.svg",
  "BR": "./public/maps/br.svg",
  "BN": "./public/maps/bn.svg",
  "BG": "./public/maps/bg.svg",
  "BF": "./public/maps/bf.svg",
  "BI": "./public/maps/bi.svg",
  "CV": "./public/maps/cv.svg",
  "KH": "./public/maps/kh.svg",
  "CM": "./public/maps/cm.svg",
  "CA": "./public/maps/ca.svg",
  "KY": "./public/maps/ky.svg",
  "CF": "./public/maps/cf.svg",
  "TD": "./public/maps/td.svg",
  "CL": "./public/maps/cl.svg",
  "CN": "./public/maps/cn.svg",
  "CO": "./public/maps/co.svg",
  "KM": "./public/maps/km.svg",
  "CG": "./public/maps/cg.svg",
  "CD": "./public/maps/cd.svg",
  "CR": "./public/maps/cr.svg",
  "CI": "./public/maps/ci.svg",
  "HR": "./public/maps/hr.svg",
  "CU": "./public/maps/cu.svg",
  "CY": "./public/maps/cy.svg",
  "CZ": "./public/maps/cz.svg",
  "DK": "./public/maps/dk.svg",
  "DJ": "./public/maps/dj.svg",
  "DM": "./public/maps/dm.svg",
  "DO": "./public/maps/do.svg",
  "EC": "./public/maps/ec.svg",
  "EG": "./public/maps/eg.svg",
  "SV": "./public/maps/sv.svg",
  "GQ": "./public/maps/gq.svg",
  "ER": "./public/maps/er.svg",
  "EE": "./public/maps/ee.svg",
  "ET": "./public/maps/et.svg",
  "FJ": "./public/maps/fj.svg",
  "FI": "./public/maps/fi.svg",
  "FR": "./public/maps/fr.svg",
  "GA": "./public/maps/ga.svg",
  "GM": "./public/maps/gm.svg",
  "GE": "./public/maps/ge.svg",
  "DE": "./public/maps/de.svg",
  "GH": "./public/maps/gh.svg",
  "GR": "./public/maps/gr.svg",
  "GD": "./public/maps/gd.svg",
  "GT": "./public/maps/gt.svg",
  "GN": "./public/maps/gn.svg",
  "GW": "./public/maps/gw.svg",
  "GY": "./public/maps/gy.svg",
  "HT": "./public/maps/ht.svg",
  "HN": "./public/maps/hn.svg",
  "HU": "./public/maps/hu.svg",
  "IS": "./public/maps/is.svg",
  "IN": "./public/maps/in.svg",
  "ID": "./public/maps/id.svg",
  "IR": "./public/maps/ir.svg",
  "IQ": "./public/maps/iq.svg",
  "IE": "./public/maps/ie.svg",
  "IL": "./public/maps/il.svg",
  "IT": "./public/maps/it.svg",
  "JM": "./public/maps/jm.svg",
  "JP": "./public/maps/jp.svg",
  "JO": "./public/maps/jo.svg",
  "KZ": "./public/maps/kz.svg",
  "KE": "./public/maps/ke.svg",
  "KI": "./public/maps/ki.svg",
  "KP": "./public/maps/kp.svg",
  "KR": "./public/maps/kr.svg",
  "KW": "./public/maps/kw.svg",
  "KG": "./public/maps/kg.svg",
  "LA": "./public/maps/la.svg",
  "LV": "./public/maps/lv.svg",
  "LB": "./public/maps/lb.svg",
  "LS": "./public/maps/ls.svg",
  "LR": "./public/maps/lr.svg",
  "LY": "./public/maps/ly.svg",
  "LI": "./public/maps/li.svg",
  "LT": "./public/maps/lt.svg",
  "LU": "./public/maps/lu.svg",
  "MG": "./public/maps/mg.svg",
  "MW": "./public/maps/mw.svg",
  "MY": "./public/maps/my.svg",
  "MV": "./public/maps/mv.svg",
  "ML": "./public/maps/ml.svg",
  "MT": "./public/maps/mt.svg",
  "MH": "./public/maps/mh.svg",
  "MR": "./public/maps/mr.svg",
  "MU": "./public/maps/mu.svg",
  "MX": "./public/maps/mx.svg",
  "FM": "./public/maps/fm.svg",
  "MD": "./public/maps/md.svg",
  "MC": "./public/maps/mc.svg",
  "MN": "./public/maps/mn.svg",
  "ME": "./public/maps/me.svg",
  "MA": "./public/maps/ma.svg",
  "MZ": "./public/maps/mz.svg",
  "MM": "./public/maps/mm.svg",
  "NA": "./public/maps/na.svg",
  "NR": "./public/maps/nr.svg",
  "NP": "./public/maps/np.svg",
  "NL": "./public/maps/nl.svg",
  "NZ": "./public/maps/nz.svg",
  "NI": "./public/maps/ni.svg",
  "NE": "./public/maps/ne.svg",
  "NG": "./public/maps/ng.svg",
  "NO": "./public/maps/no.svg",
  "OM": "./public/maps/om.svg",
  "PK": "./public/maps/pk.svg",
  "PW": "./public/maps/pw.svg",
  "PA": "./public/maps/pa.svg",
  "PG": "./public/maps/pg.svg",
  "PY": "./public/maps/py.svg",
  "PE": "./public/maps/pe.svg",
  "PH": "./public/maps/ph.svg",
  "PL": "./public/maps/pl.svg",
  "PT": "./public/maps/pt.svg",
  "QA": "./public/maps/qa.svg",
  "RO": "./public/maps/ro.svg",
  "RU": "./public/maps/ru.svg",
  "RW": "./public/maps/rw.svg",
  "WS": "./public/maps/ws.svg",
  "SM": "./public/maps/sm.svg",
  "ST": "./public/maps/st.svg",
  "SA": "./public/maps/sa.svg",
  "SN": "./public/maps/sn.svg",
  "RS": "./public/maps/rs.svg",
  "SC": "./public/maps/sc.svg",
  "SL": "./public/maps/sl.svg",
  "SG": "./public/maps/sg.svg",
  "SK": "./public/maps/sk.svg",
  "SI": "./public/maps/si.svg",
  "SB": "./public/maps/sb.svg",
  "SO": "./public/maps/so.svg",
  "ZA": "./public/maps/za.svg",
  "ES": "./public/maps/es.svg",
  "LK": "./public/maps/lk.svg",
  "SD": "./public/maps/sd.svg",
  "SR": "./public/maps/sr.svg",
  "SZ": "./public/maps/sz.svg",
  "SE": "./public/maps/se.svg",
  "CH": "./public/maps/ch.svg",
  "SY": "./public/maps/sy.svg",
  "TW": "./public/maps/tw.svg",
  "TJ": "./public/maps/tj.svg",
  "TZ": "./public/maps/tz.svg",
  "TH": "./public/maps/th.svg",
  "TL": "./public/maps/tl.svg",
  "TG": "./public/maps/tg.svg",
  "TO": "./public/maps/to.svg",
  "TT": "./public/maps/tt.svg",
  "TN": "./public/maps/tn.svg",
  "TR": "./public/maps/tr.svg",
  "TM": "./public/maps/tm.svg",
  "TV": "./public/maps/tv.svg",
  "UG": "./public/maps/ug.svg",
  "UA": "./public/maps/ua.svg",
  "AE": "./public/maps/ae.svg",
  "GB": "./public/maps/gb.svg",
  "US": "./public/maps/us.svg",
  "UY": "./public/maps/uy.svg",
  "UZ": "./public/maps/uz.svg",
  "VU": "./public/maps/vu.svg",
  "VA": "./public/maps/va.svg",
  "VE": "./public/maps/ve.svg",
  "VN": "./public/maps/vn.svg",
  "YE": "./public/maps/ye.svg",
  "ZM": "./public/maps/zm.svg",
  "ZW": "./public/maps/zw.svg"
};

const countryNameMap = {
  "AF": "Afghanistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BR": "Brazil",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Cape Verde",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo - Brazzaville",
  "CD": "Congo - Kinshasa",
  "CR": "Costa Rica",
  "CI": "Côte d’Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GR": "Greece",
  "GD": "Grenada",
  "GT": "Guatemala",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HN": "Honduras",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Laos",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "MX": "Mexico",
  "FM": "Micronesia",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar (Burma)",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PL": "Poland",
  "PT": "Portugal",
  "QA": "Qatar",
  "RO": "Romania",
  "RU": "Russia",
  "RW": "Rwanda",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé and Príncipe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SZ": "Eswatini (Swaziland)",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syria",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatican City",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

const cities = require('../node_modules/country-json/src/country-by-capital-city.json');

// Function to retrieve map image from country code
async function getMapByCountryCode(countryCode) {
  console.log("code in: ", countryCode)
  try{
    countryData = {
      "title" : countryNameMap[countryCode],
      "svgPath" : countryMap[countryCode]
    }
    console.log("svg path:", countryData.svgPath)
    return countryData;
  }
  catch(error){
    console.error("issue getting map")
  }
}

function constructCountryData(countryName, requestedData) {

}

function getCapitalCity(countryName) {
  const entry = cities.find(country => country.country.toLowerCase() === countryName.toLowerCase());
  return entry ? entry.city : null;
}

module.exports = {
  getMapByCountryCode,
  getCapitalCity
};
