const pool = require('../database/sqlConfig');


const countryMap = {
  "AF": "../maps/af.svg",
  "AL": "../maps/al.svg",
  "DZ": "../maps/dz.svg",
  "AS": "../maps/as.svg",
  "AD": "../maps/ad.svg",
  "AO": "../maps/ao.svg",
  "AI": "../maps/ai.svg",
  "AQ": "../maps/aq.svg",
  "AG": "../maps/ag.svg",
  "AR": "../maps/ar.svg",
  "AM": "../maps/am.svg",
  "AW": "../maps/aw.svg",
  "AU": "../maps/au.svg",
  "AT": "../maps/at.svg",
  "AZ": "../maps/az.svg",
  "BS": "../maps/bs.svg",
  "BH": "../maps/bh.svg",
  "BD": "../maps/bd.svg",
  "BB": "../maps/bb.svg",
  "BY": "../maps/by.svg",
  "BE": "../maps/be.svg",
  "BZ": "../maps/bz.svg",
  "BJ": "../maps/bj.svg",
  "BM": "../maps/bm.svg",
  "BT": "../maps/bt.svg",
  "BO": "../maps/bo.svg",
  "BA": "../maps/ba.svg",
  "BW": "../maps/bw.svg",
  "BR": "../maps/br.svg",
  "BN": "../maps/bn.svg",
  "BG": "../maps/bg.svg",
  "BF": "../maps/bf.svg",
  "BI": "../maps/bi.svg",
  "CV": "../maps/cv.svg",
  "KH": "../maps/kh.svg",
  "CM": "../maps/cm.svg",
  "CA": "../maps/ca.svg",
  "KY": "../maps/ky.svg",
  "CF": "../maps/cf.svg",
  "TD": "../maps/td.svg",
  "CL": "../maps/cl.svg",
  "CN": "../maps/cn.svg",
  "CO": "../maps/co.svg",
  "KM": "../maps/km.svg",
  "CG": "../maps/cg.svg",
  "CD": "../maps/cd.svg",
  "CR": "../maps/cr.svg",
  "CI": "../maps/ci.svg",
  "HR": "../maps/hr.svg",
  "CU": "../maps/cu.svg",
  "CY": "../maps/cy.svg",
  "CZ": "../maps/cz.svg",
  "DK": "../maps/dk.svg",
  "DJ": "../maps/dj.svg",
  "DM": "../maps/dm.svg",
  "DO": "../maps/do.svg",
  "EC": "../maps/ec.svg",
  "EG": "../maps/eg.svg",
  "SV": "../maps/sv.svg",
  "GQ": "../maps/gq.svg",
  "ER": "../maps/er.svg",
  "EE": "../maps/ee.svg",
  "ET": "../maps/et.svg",
  "FJ": "../maps/fj.svg",
  "FI": "../maps/fi.svg",
  "FR": "../maps/fr.svg",
  "GA": "../maps/ga.svg",
  "GM": "../maps/gm.svg",
  "GE": "../maps/ge.svg",
  "DE": "../maps/de.svg",
  "GH": "../maps/gh.svg",
  "GR": "../maps/gr.svg",
  "GD": "../maps/gd.svg",
  "GT": "../maps/gt.svg",
  "GN": "../maps/gn.svg",
  "GW": "../maps/gw.svg",
  "GY": "../maps/gy.svg",
  "HT": "../maps/ht.svg",
  "HN": "../maps/hn.svg",
  "HU": "../maps/hu.svg",
  "IS": "../maps/is.svg",
  "IN": "../maps/in.svg",
  "ID": "../maps/id.svg",
  "IR": "../maps/ir.svg",
  "IQ": "../maps/iq.svg",
  "IE": "../maps/ie.svg",
  "IL": "../maps/il.svg",
  "IT": "../maps/it.svg",
  "JM": "../maps/jm.svg",
  "JP": "../maps/jp.svg",
  "JO": "../maps/jo.svg",
  "KZ": "../maps/kz.svg",
  "KE": "../maps/ke.svg",
  "KI": "../maps/ki.svg",
  "KP": "../maps/kp.svg",
  "KR": "../maps/kr.svg",
  "KW": "../maps/kw.svg",
  "KG": "../maps/kg.svg",
  "LA": "../maps/la.svg",
  "LV": "../maps/lv.svg",
  "LB": "../maps/lb.svg",
  "LS": "../maps/ls.svg",
  "LR": "../maps/lr.svg",
  "LY": "../maps/ly.svg",
  "LI": "../maps/li.svg",
  "LT": "../maps/lt.svg",
  "LU": "../maps/lu.svg",
  "MG": "../maps/mg.svg",
  "MW": "../maps/mw.svg",
  "MY": "../maps/my.svg",
  "MV": "../maps/mv.svg",
  "ML": "../maps/ml.svg",
  "MT": "../maps/mt.svg",
  "MH": "../maps/mh.svg",
  "MR": "../maps/mr.svg",
  "MU": "../maps/mu.svg",
  "MX": "../maps/mx.svg",
  "FM": "../maps/fm.svg",
  "MD": "../maps/md.svg",
  "MC": "../maps/mc.svg",
  "MN": "../maps/mn.svg",
  "ME": "../maps/me.svg",
  "MA": "../maps/ma.svg",
  "MZ": "../maps/mz.svg",
  "MM": "../maps/mm.svg",
  "NA": "../maps/na.svg",
  "NR": "../maps/nr.svg",
  "NP": "../maps/np.svg",
  "NL": "../maps/nl.svg",
  "NZ": "../maps/nz.svg",
  "NI": "../maps/ni.svg",
  "NE": "../maps/ne.svg",
  "NG": "../maps/ng.svg",
  "NO": "../maps/no.svg",
  "OM": "../maps/om.svg",
  "PK": "../maps/pk.svg",
  "PW": "../maps/pw.svg",
  "PA": "../maps/pa.svg",
  "PG": "../maps/pg.svg",
  "PY": "../maps/py.svg",
  "PE": "../maps/pe.svg",
  "PH": "../maps/ph.svg",
  "PL": "../maps/pl.svg",
  "PT": "../maps/pt.svg",
  "QA": "../maps/qa.svg",
  "RO": "../maps/ro.svg",
  "RU": "../maps/ru.svg",
  "RW": "../maps/rw.svg",
  "WS": "../maps/ws.svg",
  "SM": "../maps/sm.svg",
  "ST": "../maps/st.svg",
  "SA": "../maps/sa.svg",
  "SN": "../maps/sn.svg",
  "RS": "../maps/rs.svg",
  "SC": "../maps/sc.svg",
  "SL": "../maps/sl.svg",
  "SG": "../maps/sg.svg",
  "SK": "../maps/sk.svg",
  "SI": "../maps/si.svg",
  "SB": "../maps/sb.svg",
  "SO": "../maps/so.svg",
  "ZA": "../maps/za.svg",
  "ES": "../maps/es.svg",
  "LK": "../maps/lk.svg",
  "SD": "../maps/sd.svg",
  "SR": "../maps/sr.svg",
  "SZ": "../maps/sz.svg",
  "SE": "../maps/se.svg",
  "CH": "../maps/ch.svg",
  "SY": "../maps/sy.svg",
  "TW": "../maps/tw.svg",
  "TJ": "../maps/tj.svg",
  "TZ": "../maps/tz.svg",
  "TH": "../maps/th.svg",
  "TL": "../maps/tl.svg",
  "TG": "../maps/tg.svg",
  "TO": "../maps/to.svg",
  "TT": "../maps/tt.svg",
  "TN": "../maps/tn.svg",
  "TR": "../maps/tr.svg",
  "TM": "../maps/tm.svg",
  "TV": "../maps/tv.svg",
  "UG": "../maps/ug.svg",
  "UA": "../maps/ua.svg",
  "AE": "../maps/ae.svg",
  "GB": "../maps/gb.svg",
  "US": "../maps/us.svg",
  "UY": "../maps/uy.svg",
  "UZ": "../maps/uz.svg",
  "VU": "../maps/vu.svg",
  "VA": "../maps/va.svg",
  "VE": "../maps/ve.svg",
  "VN": "../maps/vn.svg",
  "YE": "../maps/ye.svg",
  "ZM": "../maps/zm.svg",
  "ZW": "../maps/zw.svg"
};

const countryNameMap = {
  "AF": "Afghanistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BR": "Brazil",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Cape Verde",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo - Brazzaville",
  "CD": "Congo - Kinshasa",
  "CR": "Costa Rica",
  "CI": "Côte d’Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GR": "Greece",
  "GD": "Grenada",
  "GT": "Guatemala",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HN": "Honduras",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Laos",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "MX": "Mexico",
  "FM": "Micronesia",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar (Burma)",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PL": "Poland",
  "PT": "Portugal",
  "QA": "Qatar",
  "RO": "Romania",
  "RU": "Russia",
  "RW": "Rwanda",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé and Príncipe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SZ": "Eswatini (Swaziland)",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syria",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatican City",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};


// Function to retrieve map image from country code
async function getMapByCountryCode(countryCode) {
  
  try{
    countryData = {
      "title" : countryNameMap[countryCode],
      "svgPath" : countryMap[countryCode]
    }
    return countryData;
  }
  catch(error){
    console.error("issue getting map")
  }
}

module.exports = {
  getMapByCountryCode
};
