const pool = require('../database/sqlConfig');


const countryMap = {
  "AF": "./public/maps/af.svg",
  "AL": "./public/maps/al.svg",
  "DZ": "./public/maps/dz.svg",
  "AS": "./public/maps/as.svg",
  "AD": "./public/maps/ad.svg",
  "AO": "./public/maps/ao.svg",
  "AI": "./public/maps/ai.svg",
  "AQ": "./public/maps/aq.svg",
  "AG": "./public/maps/ag.svg",
  "AR": "./public/maps/ar.svg",
  "AM": "./public/maps/am.svg",
  "AW": "./public/maps/aw.svg",
  "AU": "./public/maps/au.svg",
  "AT": "./public/maps/at.svg",
  "AZ": "./public/maps/az.svg",
  "BS": "./public/maps/bs.svg",
  "BH": "./public/maps/bh.svg",
  "BD": "./public/maps/bd.svg",
  "BB": "./public/maps/bb.svg",
  "BY": "./public/maps/by.svg",
  "BE": "./public/maps/be.svg",
  "BZ": "./public/maps/bz.svg",
  "BJ": "./public/maps/bj.svg",
  "BM": "./public/maps/bm.svg",
  "BT": "./public/maps/bt.svg",
  "BO": "./public/maps/bo.svg",
  "BA": "./public/maps/ba.svg",
  "BW": "./public/maps/bw.svg",
  "BR": "./public/maps/br.svg",
  "BN": "./public/maps/bn.svg",
  "BG": "./public/maps/bg.svg",
  "BF": "./public/maps/bf.svg",
  "BI": "./public/maps/bi.svg",
  "CV": "./public/maps/cv.svg",
  "KH": "./public/maps/kh.svg",
  "CM": "./public/maps/cm.svg",
  "CA": "./public/maps/ca.svg",
  "KY": "./public/maps/ky.svg",
  "CF": "./public/maps/cf.svg",
  "TD": "./public/maps/td.svg",
  "CL": "./public/maps/cl.svg",
  "CN": "./public/maps/cn.svg",
  "CO": "./public/maps/co.svg",
  "KM": "./public/maps/km.svg",
  "CG": "./public/maps/cg.svg",
  "CD": "./public/maps/cd.svg",
  "CR": "./public/maps/cr.svg",
  "CI": "./public/maps/ci.svg",
  "HR": "./public/maps/hr.svg",
  "CU": "./public/maps/cu.svg",
  "CY": "./public/maps/cy.svg",
  "CZ": "./public/maps/cz.svg",
  "DK": "./public/maps/dk.svg",
  "DJ": "./public/maps/dj.svg",
  "DM": "./public/maps/dm.svg",
  "DO": "./public/maps/do.svg",
  "EC": "./public/maps/ec.svg",
  "EG": "./public/maps/eg.svg",
  "SV": "./public/maps/sv.svg",
  "GQ": "./public/maps/gq.svg",
  "ER": "./public/maps/er.svg",
  "EE": "./public/maps/ee.svg",
  "ET": "./public/maps/et.svg",
  "FJ": "./public/maps/fj.svg",
  "FI": "./public/maps/fi.svg",
  "FR": "./public/maps/fr.svg",
  "GA": "./public/maps/ga.svg",
  "GM": "./public/maps/gm.svg",
  "GE": "./public/maps/ge.svg",
  "DE": "./public/maps/de.svg",
  "GH": "./public/maps/gh.svg",
  "GR": "./public/maps/gr.svg",
  "GD": "./public/maps/gd.svg",
  "GT": "./public/maps/gt.svg",
  "GN": "./public/maps/gn.svg",
  "GW": "./public/maps/gw.svg",
  "GY": "./public/maps/gy.svg",
  "HT": "./public/maps/ht.svg",
  "HN": "./public/maps/hn.svg",
  "HU": "./public/maps/hu.svg",
  "IS": "./public/maps/is.svg",
  "IN": "./public/maps/in.svg",
  "ID": "./public/maps/id.svg",
  "IR": "./public/maps/ir.svg",
  "IQ": "./public/maps/iq.svg",
  "IE": "./public/maps/ie.svg",
  "IL": "./public/maps/il.svg",
  "IT": "./public/maps/it.svg",
  "JM": "./public/maps/jm.svg",
  "JP": "./public/maps/jp.svg",
  "JO": "./public/maps/jo.svg",
  "KZ": "./public/maps/kz.svg",
  "KE": "./public/maps/ke.svg",
  "KI": "./public/maps/ki.svg",
  "KP": "./public/maps/kp.svg",
  "KR": "./public/maps/kr.svg",
  "KW": "./public/maps/kw.svg",
  "KG": "./public/maps/kg.svg",
  "LA": "./public/maps/la.svg",
  "LV": "./public/maps/lv.svg",
  "LB": "./public/maps/lb.svg",
  "LS": "./public/maps/ls.svg",
  "LR": "./public/maps/lr.svg",
  "LY": "./public/maps/ly.svg",
  "LI": "./public/maps/li.svg",
  "LT": "./public/maps/lt.svg",
  "LU": "./public/maps/lu.svg",
  "MG": "./public/maps/mg.svg",
  "MW": "./public/maps/mw.svg",
  "MY": "./public/maps/my.svg",
  "MV": "./public/maps/mv.svg",
  "ML": "./public/maps/ml.svg",
  "MT": "./public/maps/mt.svg",
  "MH": "./public/maps/mh.svg",
  "MR": "./public/maps/mr.svg",
  "MU": "./public/maps/mu.svg",
  "MX": "./public/maps/mx.svg",
  "FM": "./public/maps/fm.svg",
  "MD": "./public/maps/md.svg",
  "MC": "./public/maps/mc.svg",
  "MN": "./public/maps/mn.svg",
  "ME": "./public/maps/me.svg",
  "MA": "./public/maps/ma.svg",
  "MZ": "./public/maps/mz.svg",
  "MM": "./public/maps/mm.svg",
  "NA": "./public/maps/na.svg",
  "NR": "./public/maps/nr.svg",
  "NP": "./public/maps/np.svg",
  "NL": "./public/maps/nl.svg",
  "NZ": "./public/maps/nz.svg",
  "NI": "./public/maps/ni.svg",
  "NE": "./public/maps/ne.svg",
  "NG": "./public/maps/ng.svg",
  "NO": "./public/maps/no.svg",
  "OM": "./public/maps/om.svg",
  "PK": "./public/maps/pk.svg",
  "PW": "./public/maps/pw.svg",
  "PA": "./public/maps/pa.svg",
  "PG": "./public/maps/pg.svg",
  "PY": "./public/maps/py.svg",
  "PE": "./public/maps/pe.svg",
  "PH": "./public/maps/ph.svg",
  "PL": "./public/maps/pl.svg",
  "PT": "./public/maps/pt.svg",
  "QA": "./public/maps/qa.svg",
  "RO": "./public/maps/ro.svg",
  "RU": "./public/maps/ru.svg",
  "RW": "./public/maps/rw.svg",
  "WS": "./public/maps/ws.svg",
  "SM": "./public/maps/sm.svg",
  "ST": "./public/maps/st.svg",
  "SA": "./public/maps/sa.svg",
  "SN": "./public/maps/sn.svg",
  "RS": "./public/maps/rs.svg",
  "SC": "./public/maps/sc.svg",
  "SL": "./public/maps/sl.svg",
  "SG": "./public/maps/sg.svg",
  "SK": "./public/maps/sk.svg",
  "SI": "./public/maps/si.svg",
  "SB": "./public/maps/sb.svg",
  "SO": "./public/maps/so.svg",
  "ZA": "./public/maps/za.svg",
  "ES": "./public/maps/es.svg",
  "LK": "./public/maps/lk.svg",
  "SD": "./public/maps/sd.svg",
  "SR": "./public/maps/sr.svg",
  "SZ": "./public/maps/sz.svg",
  "SE": "./public/maps/se.svg",
  "CH": "./public/maps/ch.svg",
  "SY": "./public/maps/sy.svg",
  "TW": "./public/maps/tw.svg",
  "TJ": "./public/maps/tj.svg",
  "TZ": "./public/maps/tz.svg",
  "TH": "./public/maps/th.svg",
  "TL": "./public/maps/tl.svg",
  "TG": "./public/maps/tg.svg",
  "TO": "./public/maps/to.svg",
  "TT": "./public/maps/tt.svg",
  "TN": "./public/maps/tn.svg",
  "TR": "./public/maps/tr.svg",
  "TM": "./public/maps/tm.svg",
  "TV": "./public/maps/tv.svg",
  "UG": "./public/maps/ug.svg",
  "UA": "./public/maps/ua.svg",
  "AE": "./public/maps/ae.svg",
  "GB": "./public/maps/gb.svg",
  "US": "./public/maps/us.svg",
  "UY": "./public/maps/uy.svg",
  "UZ": "./public/maps/uz.svg",
  "VU": "./public/maps/vu.svg",
  "VA": "./public/maps/va.svg",
  "VE": "./public/maps/ve.svg",
  "VN": "./public/maps/vn.svg",
  "YE": "./public/maps/ye.svg",
  "ZM": "./public/maps/zm.svg",
  "ZW": "./public/maps/zw.svg"
};

const countryNameMap = {
  "AF": "Afghanistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AQ": "Antarctica",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BR": "Brazil",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "CV": "Cape Verde",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo - Brazzaville",
  "CD": "Congo - Kinshasa",
  "CR": "Costa Rica",
  "CI": "Côte d’Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CY": "Cyprus",
  "CZ": "Czechia",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GR": "Greece",
  "GD": "Grenada",
  "GT": "Guatemala",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HN": "Honduras",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "KP": "North Korea",
  "KR": "South Korea",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Laos",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "MX": "Mexico",
  "FM": "Micronesia",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar (Burma)",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PL": "Poland",
  "PT": "Portugal",
  "QA": "Qatar",
  "RO": "Romania",
  "RU": "Russia",
  "RW": "Rwanda",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé and Príncipe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "ZA": "South Africa",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SZ": "Eswatini (Swaziland)",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syria",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TL": "Timor-Leste",
  "TG": "Togo",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TM": "Turkmenistan",
  "TV": "Tuvalu",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatican City",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

const countrySummaryMap = {
  "AF": "Afghanistan is known for its rich cultural heritage and beautiful landscapes.",
  "AL": "Albania boasts stunning Adriatic and Ionian coastlines and a vibrant history.",
  "DZ": "Algeria is famed for its Sahara Desert landscapes and ancient ruins.",
  "AS": "American Samoa is a tropical paradise with vibrant Polynesian culture.",
  "AD": "Andorra offers breathtaking mountain views and excellent ski resorts.",
  "AO": "Angola features diverse wildlife and rich cultural traditions.",
  "AI": "Anguilla is known for its pristine beaches and crystal-clear waters.",
  "AQ": "Antarctica is the world's southernmost continent, a land of ice and unique wildlife.",
  "AG": "Antigua and Barbuda are famous for their beautiful beaches and clear waters.",
  "AR": "Argentina is renowned for its tango music and dance, and diverse landscapes.",
  "AM": "Armenia has a rich history, ancient monasteries, and beautiful mountainous scenery.",
  "AW": "Aruba is a Caribbean island paradise known for its white-sand beaches.",
  "AU": "Australia is famous for its unique wildlife, Great Barrier Reef, and Outback.",
  "AT": "Austria is celebrated for its alpine landscapes, classical music, and vibrant culture.",
  "AZ": "Azerbaijan is known for its blend of modern and ancient architecture, and rich cultural heritage.",
  "BS": "The Bahamas are renowned for their stunning beaches and vibrant marine life.",
  "BH": "Bahrain is a small island nation known for its rich history and modern skyline.",
  "BD": "Bangladesh is known for its lush greenery and rich cultural traditions.",
  "BB": "Barbados is a Caribbean gem known for its beautiful beaches and vibrant culture.",
  "BY": "Belarus offers beautiful forests, lakes, and historic castles.",
  "BE": "Belgium is famous for its medieval towns, Renaissance architecture, and delicious chocolate.",
  "BZ": "Belize is known for its stunning barrier reef and rich marine biodiversity.",
  "BJ": "Benin is rich in cultural heritage and home to vibrant traditional festivals.",
  "BM": "Bermuda is famous for its pink-sand beaches and crystal-clear waters.",
  "BT": "Bhutan is known for its breathtaking mountain scenery and Buddhist culture.",
  "BO": "Bolivia offers diverse landscapes from the Andes to the Amazon Basin.",
  "BA": "Bosnia and Herzegovina is known for its beautiful rivers and vibrant cultural heritage.",
  "BW": "Botswana is celebrated for its wildlife and stunning natural reserves.",
  "BR": "Brazil is famous for its lively culture, Carnival festival, and the Amazon rainforest.",
  "BN": "Brunei is a wealthy nation known for its beautiful mosques and rich culture.",
  "BG": "Bulgaria is known for its Black Sea beaches and historic monasteries.",
  "BF": "Burkina Faso is rich in cultural traditions and known for its vibrant art scene.",
  "BI": "Burundi is known for its beautiful landscapes and vibrant cultural traditions.",
  "CV": "Cape Verde is known for its stunning islands and vibrant music scene.",
  "KH": "Cambodia is famous for its ancient temples, including Angkor Wat.",
  "CM": "Cameroon boasts diverse landscapes and rich cultural traditions.",
  "CA": "Canada is renowned for its stunning natural beauty and welcoming multicultural society.",
  "KY": "The Cayman Islands are known for their beautiful beaches and world-class diving spots.",
  "CF": "The Central African Republic is rich in natural beauty and cultural diversity.",
  "TD": "Chad is known for its dramatic landscapes and rich cultural heritage.",
  "CL": "Chile is famous for its long coastline, Andean mountains, and vibrant culture.",
  "CN": "China boasts a rich history, diverse landscapes, and vibrant cultural heritage.",
  "CO": "Colombia is known for its beautiful landscapes, coffee, and vibrant music and dance.",
  "KM": "Comoros is an island paradise known for its stunning beaches and volcanic landscapes.",
  "CG": "Congo - Brazzaville is rich in cultural traditions and natural beauty.",
  "CD": "Congo - Kinshasa is known for its vast rainforests and rich cultural heritage.",
  "CR": "Costa Rica is renowned for its biodiversity, stunning beaches, and eco-tourism.",
  "CI": "Côte d’Ivoire is known for its vibrant culture and beautiful coastal scenery.",
  "HR": "Croatia boasts stunning Adriatic coastline and historic medieval towns.",
  "CU": "Cuba is famous for its vibrant culture, music, and beautiful beaches.",
  "CY": "Cyprus offers beautiful Mediterranean beaches and a rich cultural heritage.",
  "CZ": "Czechia is known for its historic cities, beautiful architecture, and cultural traditions.",
  "DK": "Denmark is celebrated for its high quality of life, design, and rich history.",
  "DJ": "Djibouti boasts stunning landscapes and rich cultural traditions.",
  "DM": "Dominica is known for its lush rainforests and beautiful waterfalls.",
  "DO": "The Dominican Republic offers beautiful beaches and vibrant culture.",
  "EC": "Ecuador is rich in biodiversity and home to the stunning Galápagos Islands.",
  "EG": "Egypt is famous for its ancient pyramids, Nile River, and rich history.",
  "SV": "El Salvador is known for its beautiful beaches and vibrant cultural traditions.",
  "GQ": "Equatorial Guinea boasts lush rainforests and rich cultural heritage.",
  "ER": "Eritrea is known for its stunning Red Sea coastline and cultural diversity.",
  "EE": "Estonia is known for its digital advancements and beautiful medieval cities.",
  "ET": "Ethiopia boasts a rich history, diverse landscapes, and vibrant culture.",
  "FJ": "Fiji is a tropical paradise known for its stunning beaches and vibrant marine life.",
  "FI": "Finland is celebrated for its beautiful lakes, forests, and high quality of life.",
  "FR": "France is renowned for its culture, cuisine, art, and beautiful landscapes.",
  "GA": "Gabon is rich in natural beauty with its rainforests and diverse wildlife.",
  "GM": "The Gambia is known for its beautiful beaches and vibrant culture.",
  "GE": "Georgia offers stunning mountain scenery and rich cultural heritage.",
  "DE": "Germany is known for its rich history, cultural heritage, and beautiful landscapes.",
  "GH": "Ghana is celebrated for its rich culture, history, and beautiful coastlines.",
  "GR": "Greece is famous for its ancient history, beautiful islands, and vibrant culture.",
  "GD": "Grenada is known as the 'Spice Isle' for its aromatic spice plantations and beautiful beaches.",
  "GT": "Guatemala is rich in Mayan heritage and natural beauty.",
  "GN": "Guinea boasts diverse landscapes and vibrant cultural traditions.",
  "GW": "Guinea-Bissau is known for its beautiful islands and cultural heritage.",
  "GY": "Guyana is rich in natural beauty with its rainforests and waterfalls.",
  "HT": "Haiti is known for its vibrant culture, art, and history.",
  "HN": "Honduras offers beautiful Caribbean beaches and rich cultural traditions.",
  "HU": "Hungary is celebrated for its historic architecture and vibrant culture.",
  "IS": "Iceland is known for its stunning volcanic landscapes and geothermal features.",
  "IN": "India is renowned for its diverse cultures, vibrant traditions, and rich history.",
  "ID": "Indonesia is famous for its beautiful islands, diverse cultures, and vibrant marine life.",
  "IR": "Iran boasts a rich history, ancient architecture, and vibrant cultural heritage.",
  "IQ": "Iraq is known for its rich history and cultural heritage.",
  "IE": "Ireland is famous for its lush green landscapes and rich cultural traditions.",
  "IL": "Israel is known for its historic sites and vibrant cultural heritage.",
  "IT": "Italy is celebrated for its rich history, art, cuisine, and beautiful landscapes.",
  "JM": "Jamaica is known for its reggae music, beautiful beaches, and vibrant culture.",
  "JP": "Japan is renowned for its blend of traditional and modern culture, and beautiful landscapes.",
  "JO": "Jordan is known for its ancient history and stunning desert landscapes.",
  "KZ": "Kazakhstan boasts vast steppes and rich cultural heritage.",
  "KE": "Kenya is famous for its diverse wildlife and stunning natural landscapes.",
  "KI": "Kiribati is known for its beautiful atolls and vibrant marine life.",
  "KP": "North Korea has a unique cultural heritage and historical significance.",
  "KR": "South Korea is renowned for its advanced technology and rich cultural traditions.",
  "KW": "Kuwait is known for its modern architecture and rich cultural heritage.",
  "KG": "Kyrgyzstan offers stunning mountainous landscapes and rich cultural traditions.",
  "LA": "Laos is known for its beautiful landscapes and rich cultural heritage.",
  "LV": "Latvia boasts beautiful natural landscapes and vibrant cultural traditions.",
  "LB": "Lebanon is known for its rich history, vibrant culture, and beautiful landscapes.",
  "LS": "Lesotho offers stunning mountain scenery and rich cultural traditions.",
  "LR": "Liberia is rich in cultural heritage and natural beauty.",
  "LY": "Libya boasts stunning desert landscapes and rich historical sites.",
  "LI": "Liechtenstein is known for its beautiful alpine scenery and rich cultural heritage.",
  "LT": "Lithuania is known for its beautiful landscapes and vibrant cultural traditions.",
  "LU": "Luxembourg offers a blend of modern and historical architecture and beautiful landscapes.",
  "MG": "Madagascar is renowned for its unique biodiversity and stunning landscapes.",
  "MW": "Malawi is known as the 'Warm Heart of Africa' for its friendly people and beautiful landscapes.",
  "MY": "Malaysia is famous for its diverse cultures and stunning natural beauty.",
  "MV": "The Maldives are renowned for their beautiful islands and vibrant marine life.",
  "ML": "Mali is rich in cultural heritage and historical significance.",
  "MT": "Malta boasts beautiful Mediterranean landscapes and rich cultural heritage.",
  "MH": "The Marshall Islands are known for their stunning atolls and vibrant marine life.",
  "MR": "Mauritania offers dramatic desert landscapes and rich cultural heritage.",
  "MU": "Mauritius is known for its beautiful beaches and diverse cultural traditions.",
  "MX": "Mexico is renowned for its vibrant culture, rich history, and beautiful landscapes.",
  "FM": "Micronesia boasts beautiful islands and rich cultural traditions.",
  "MD": "Moldova is known for its beautiful landscapes and rich cultural heritage.",
  "MC": "Monaco is famous for its luxurious lifestyle and stunning Mediterranean coastline.",
  "MN": "Mongolia offers vast steppes and rich cultural traditions.",
  "ME": "Montenegro is known for its stunning Adriatic coastline and beautiful landscapes.",
  "MA": "Morocco boasts rich cultural heritage and diverse landscapes.",
  "MZ": "Mozambique is known for its beautiful beaches and vibrant marine life.",
  "MM": "Myanmar (Burma) is rich in cultural heritage and beautiful landscapes.",
  "NA": "Namibia offers stunning desert landscapes and rich cultural heritage.",
  "NR": "Nauru is known for its beautiful island landscapes and vibrant marine life.",
  "NP": "Nepal is renowned for its majestic Himalayan mountains and rich cultural heritage.",
  "NL": "The Netherlands is famous for its beautiful canals, tulips, and vibrant cultural heritage.",
  "NZ": "New Zealand offers stunning natural landscapes and vibrant Maori culture.",
  "NI": "Nicaragua is known for its beautiful lakes and rich cultural traditions.",
  "NE": "Niger boasts dramatic desert landscapes and rich cultural heritage.",
  "NG": "Nigeria is renowned for its vibrant culture and diverse landscapes.",
  "NO": "Norway is famous for its stunning fjords and high quality of life.",
  "OM": "Oman is known for its beautiful desert landscapes and rich cultural heritage.",
  "PK": "Pakistan offers stunning mountain scenery and rich cultural traditions.",
  "PW": "Palau is renowned for its beautiful islands and vibrant marine life.",
  "PA": "Panama is known for its stunning canal and beautiful landscapes.",
  "PG": "Papua New Guinea boasts diverse cultures and rich natural beauty.",
  "PY": "Paraguay is known for its beautiful landscapes and vibrant cultural traditions.",
  "PE": "Peru is famous for its ancient history, diverse landscapes, and rich cultural heritage.",
  "PH": "The Philippines offers beautiful islands and rich cultural traditions.",
  "PL": "Poland is known for its rich history, beautiful architecture, and vibrant cultural heritage.",
  "PT": "Portugal is celebrated for its beautiful landscapes, rich history, and vibrant culture.",
  "QA": "Qatar is known for its modern architecture and rich cultural heritage.",
  "RO": "Romania boasts beautiful landscapes and rich cultural traditions.",
  "RU": "Russia is renowned for its vast landscapes and rich cultural heritage.",
  "RW": "Rwanda is known for its stunning landscapes and vibrant culture.",
  "WS": "Samoa offers beautiful island landscapes and rich cultural traditions.",
  "SM": "San Marino boasts beautiful medieval architecture and rich history.",
  "ST": "São Tomé and Príncipe is known for its beautiful islands and vibrant culture.",
  "SA": "Saudi Arabia is renowned for its rich cultural heritage and dramatic landscapes.",
  "SN": "Senegal is known for its vibrant culture and beautiful coastlines.",
  "RS": "Serbia boasts rich cultural traditions and beautiful landscapes.",
  "SC": "Seychelles is famous for its stunning beaches and vibrant marine life.",
  "SL": "Sierra Leone is known for its beautiful landscapes and rich cultural heritage.",
  "SG": "Singapore is renowned for its modern skyline and vibrant multicultural society.",
  "SK": "Slovakia offers beautiful landscapes and rich cultural traditions.",
  "SI": "Slovenia is known for its stunning natural beauty and rich cultural heritage.",
  "SB": "The Solomon Islands boast beautiful islands and vibrant marine life.",
  "SO": "Somalia is known for its rich cultural traditions and beautiful landscapes.",
  "ZA": "South Africa is famous for its diverse landscapes and rich cultural heritage.",
  "ES": "Spain is renowned for its vibrant culture, rich history, and beautiful landscapes.",
  "LK": "Sri Lanka boasts beautiful beaches and rich cultural heritage.",
  "SD": "Sudan is known for its rich history and diverse cultures.",
  "SR": "Suriname offers beautiful rainforests and rich cultural traditions.",
  "SZ": "Eswatini (Swaziland) is known for its stunning landscapes and vibrant cultural heritage.",
  "SE": "Sweden is famous for its high quality of life and beautiful natural landscapes.",
  "CH": "Switzerland is renowned for its stunning alpine scenery and high quality of life.",
  "SY": "Syria boasts rich cultural heritage and historical significance.",
  "TW": "Taiwan is known for its vibrant culture and beautiful landscapes.",
  "TJ": "Tajikistan offers stunning mountainous landscapes and rich cultural traditions.",
  "TZ": "Tanzania is famous for its diverse wildlife and beautiful landscapes.",
  "TH": "Thailand is renowned for its vibrant culture, beautiful beaches, and delicious cuisine.",
  "TL": "Timor-Leste boasts beautiful beaches and rich cultural heritage.",
  "TG": "Togo offers beautiful landscapes and vibrant cultural traditions.",
  "TO": "Tonga is known for its beautiful islands and rich cultural heritage.",
  "TT": "Trinidad and Tobago is famous for its vibrant culture and beautiful beaches.",
  "TN": "Tunisia is known for its rich history and beautiful Mediterranean coastline.",
  "TR": "Turkey is renowned for its rich history, vibrant culture, and diverse landscapes.",
  "TM": "Turkmenistan boasts beautiful desert landscapes and rich cultural heritage.",
  "TV": "Tuvalu offers beautiful atolls and vibrant marine life.",
  "UG": "Uganda is known for its diverse wildlife and stunning natural beauty.",
  "UA": "Ukraine boasts beautiful landscapes and rich cultural heritage.",
  "AE": "The United Arab Emirates is famous for its modern architecture and vibrant culture.",
  "GB": "The United Kingdom is renowned for its rich history, vibrant culture, and beautiful landscapes.",
  "US": "The United States is known for its diverse landscapes and vibrant culture.",
  "UY": "Uruguay is celebrated for its beautiful beaches and rich cultural traditions.",
  "UZ": "Uzbekistan boasts rich cultural heritage and stunning architecture.",
  "VU": "Vanuatu is known for its beautiful islands and vibrant marine life.",
  "VA": "Vatican City is famous for its rich history and stunning architecture.",
  "VE": "Venezuela offers stunning landscapes and rich cultural heritage.",
  "VN": "Vietnam is renowned for its vibrant culture, beautiful landscapes, and delicious cuisine.",
  "YE": "Yemen boasts rich history and beautiful architecture.",
  "ZM": "Zambia is known for its stunning landscapes and diverse wildlife.",
  "ZW": "Zimbabwe offers beautiful natural landscapes and rich cultural heritage."
};

const countryCodeMap = Object.fromEntries(
  Object.entries(countryNameMap).map(([code, name]) => [name, code])
);


const cities = require('../node_modules/country-json/src/country-by-capital-city.json');
const population = require('../node_modules/country-json/src/country-by-population.json');
const density = require('../node_modules/country-json/src/country-by-population-density.json');
const area = require('../node_modules/country-json/src/country-by-surface-area.json');
const temp = require('../node_modules/country-json/src/country-by-yearly-average-temperature.json');


async function getSVGByCountryName(countryName){
  const countryCode = countryCodeMap[countryName];
  const svgpath = countryMap[countryCode]
  return svgpath;
}

// Function to retrieve map image from country code
// works
async function getMapByCountryCode(countryCode) {
  try{
    countryData = {
      "title" : countryNameMap[countryCode],
      "svgPath" : countryMap[countryCode]
    }
    return countryData;
  }
  catch(error){
    console.error("issue getting map")
  }
}


function constructCarouselData() {
  const keys = Object.keys(countryMap);
  
  // Generate 3 random unique indices
  const indices = [];
  while (indices.length < 3) {
    const index = Math.floor(Math.random() * keys.length);
    if (!indices.includes(index)) {
      indices.push(index);
    }
  }

  const urls = [];
  const names = [];
  const summaries = [];

  indices.forEach(index => {
    const countryCode = keys[index];
    urls.push(countryCode);  // Store the uppercase country code
    names.push(countryNameMap[countryCode]);  // Store the country name
    summaries.push(countrySummaryMap[countryCode]);  // Store the country summary
  });

  // Pack the data into a return JSON object
  return {
    urls: urls,
    names: names,
    summaries: summaries
  };
}

function constructCountryData(requestedData) {
  country = requestedData;
  data = {
    city : getCapitalCity(country),
    population : getPopulation(country),
    density : getDensity(country),
    area : getArea(country),
    temp : getTemp(country)
  }
  console.log("constructed country data: ", data)
  return data;
}

function getCapitalCity(countryName) {
  const entry = cities.find(country => country.country.toLowerCase() === countryName.toLowerCase());
  return entry ? entry.city : null;
}

function getPopulation(countryName) {
  const entry = population.find(country => country.country.toLowerCase() === countryName.toLowerCase());
  return entry ? entry.population : null;
}

function getDensity(countryName) {
  const entry = density.find(country => country.country.toLowerCase() === countryName.toLowerCase());
  return entry ? entry.density : null;
}

function getArea(countryName) {
  const entry = area.find(country => country.country.toLowerCase() === countryName.toLowerCase());
  return entry ? entry.area : null;
}

function getTemp(countryName) {
  const entry = temp.find(country => country.country.toLowerCase() === countryName.toLowerCase());
  return entry ? entry.temperature : null;
}


module.exports = {
  getMapByCountryCode,
  getCapitalCity,
  constructCountryData,
  constructCarouselData,
  getSVGByCountryName
};
